# MVC CONFIGURATION:

server:
  port: 8082
  use-forward-headers: true
  servlet:
    context-path: /
    session:
      timeout: 1d

# NO PERSISTENCE NECESSARY. ADMINS ARE MANAGED THROUGH NHS BACKEND REST API.
